library(dplyr)
library(ggplot2)

root = '/scratch/genevol/users/lucas/Vif/'
rootSave = '/raid/genevol/users/lucas/heritability/00.Descriptive/Images/Hardy/'

##################################################################################################################################
# Compilation of MAF and HWE calculations by snp and chromosome generated by previous programs
# Based on different cutpoints, the objective is to generate lists of snps to enter in posterior pruning analysis - VIF
##################################################################################################################################

ct_ = 0
files_processed = as.data.frame(list.files(root))
filesNP = c()
colnames(files_processed) = 'file'
listPruned = files_processed %>% filter(grepl('\\.prune\\.in',file))
# Reading HWE files and SNP's mappings
for(chr_ in 1:22){
  for(hwe_ in c(.05 , 1e-2 , 1e-3 , 1e-4 , 1e-5 , 1e-6 , 1e-7 , 1e-8 )){
    for(maf_ in c(.001 , .005 , (1:5)/100)){
      for(vif_ in c(1.11,2.5,5)){
        for(pop_ in c('NAfr','Geuvadis','Full')){

          print(paste0(ct_,' Chromosome: ',chr_,';Hwe: ',hwe_,';Maf: ',maf_,';Pop: ',pop_,';Vif: ',vif_))
          file_ = paste0('Vif_',pop_,'_chr',chr_,'_maf_',maf_,'_hwe_',hwe_,'_vif_',vif_,'.prune.in')
          # Reading all filtered snps
          if (file_ %in% listPruned$file){
            totSnps = read.table(paste0(root,file_) , sep = '\t' , header = T) %>%  
            # Assimilating values to df
            summarise(n = n()) %>% 
            mutate(Chr = chr_ , Sample = pop_ , Maf = maf_ , Hwe = hwe_ , Vif = vif_)
            if(ct_ == 0){
              Df = totSnps
            }else{
              Df = rbind(Df , totSnps)
            }
            ct_ = ct_ + 1
          } else{
            filesNP = c(filesNP,file_)
            print('Out î')
          }
        }
      }
    }
  }
}

dfQ = as.data.frame(filesNP)
colnames(dfQ) = c('file')
for(i in 1:nrow(dfQ)){
  breakStr = stringr::str_split(dfQ[i,'file'],'_')[[1]]
  dfQ[i,'pop'] = breakStr[2]
  dfQ[i,'chr'] = as.numeric(gsub('chr','',breakStr[3]))
  dfQ[i,'maf'] = as.numeric(breakStr[5])
  dfQ[i,'hwe'] = as.numeric(breakStr[7])
  dfQ[i,'vif'] = as.numeric(stringr::str_split(breakStr[9],'\\.')[[1]][1])

}
df_ = dfQ[dfQ$pop == 'NAfr',]
samp = '/raid/genevol/users/lucas/heritability/02.GCTA/data/nAfr.txt'
for(i in 1:nrow(df_)){
  print(df_$file[i])
  outputVif=paste0("/scratch/genevol/users/lucas/Vif/Vif_NAfr_chr",df_$chr[i],"_maf_",df_$maf[i],"_hwe_",df_$hwe[i],"_vif_",df_$vif[i])
  com_ = paste0('plink --vcf /raid/genevol/vcf_1000G/phase3_20130502_grch38positions/ALL.chr', df_$chr[i],'_GRCh38.genotypes.20170504.vcf.gz --indep 50 5 ', df_$vif[i] ,' --extract /scratch/genevol/users/lucas/ListSnpFilters/filter_sample_NAfr_maf_',df_$maf[i],'_hwe_',df_$hwe[i],'.txt --vcf-half-call missing --keep ' , samp ,' --out ' , outputVif)
  system(command = com_,intern = T)
}

df_ = dfQ[dfQ$pop == 'Geuvadis',]
samp = '/raid/genevol/users/lucas/heritability/02.GCTA/data/samples.txt'
for(i in 1:nrow(df_)){
  print(df_$file[i])
  outputVif=paste0("/scratch/genevol/users/lucas/Vif/Vif_Geuvadis_chr",df_$chr[i],"_maf_",df_$maf[i],"_hwe_",df_$hwe[i],"_vif_",df_$vif[i])
  com_ = paste0('plink --vcf /raid/genevol/vcf_1000G/phase3_20130502_grch38positions/ALL.chr', df_$chr[i],'_GRCh38.genotypes.20170504.vcf.gz --indep 50 5 ', df_$vif[i] ,' --extract /scratch/genevol/users/lucas/ListSnpFilters/filter_sample_Geuvadis_maf_',df_$maf[i],'_hwe_',df_$hwe[i],'.txt --vcf-half-call missing --keep ' , samp ,' --out ' , outputVif)
  system(command = com_,intern = T)
}


comb = Df  %>% group_by(Sample,Maf,Hwe,Vif) %>% summarise(sum_ = sum(n))

plotVol = Df %>% ggplot(aes(x = Chr,y=log10(n) , colour = as.factor(Hwe) , linetype = as.factor(Maf) , shape = as.factor(Vif) )) + 
geom_line() +
geom_point() +
facet_wrap(~Sample,ncol = 1) +
theme_bw() +
theme( 
      panel.border = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank()
    ) +
labs(x = 'Chromosome',y= expression(Frequency ~ (log[10]) ) , colour = 'HWE',linetype = 'MAF')

ggsave(paste0(rootSave,'combinedFiltersFinal',".png"), plotVol, bg = "transparent",width=10, height=8, dpi=300)


plotVolMarg = comb %>% ggplot(aes(x = -log10(Hwe),y=100*sum_/88000000 , colour = as.factor(Maf) , shape = as.factor(Vif) )) + 
facet_wrap(~Sample, ncol = 1) +
geom_line() +
geom_point(size = 3) +
theme_bw() +
theme( 
      panel.border = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank()
    ) +
labs(x = expression( HWE~ (-log[10]) ),y= 'Relative size of set' , colour = 'MAF')+
scale_y_continuous(breaks = 2*c(0:12) , labels = paste0(2*c(0:12),'%'))
ggsave(paste0(rootSave,'combinedFiltersMargFinal',".png"), plotVolMarg, bg = "transparent",width=10, height=8, dpi=300)




# merge between hwe test and SNP positions
finalPltDfHwe = merge(hweDf,refDf)
# merge between MAF and SNP positions
finalPltDf = merge(finalPltDfHwe,mafDf , by = c("CHR","SNP","Sample") , all.x = T , all.y = T)

# Cutpoints and filters 
samples_ = c('NAfr','Geuvadis','Full')
hwes_ = c(.05 , 1e-2 , 1e-3 , 1e-4 , 1e-5 , 1e-6 , 1e-7 , 1e-8 )
mafs_ = c(.001 , .005 , (1:5)/100)

# Generating list of snps 
cont = 0
for(sample_ in samples_){
  for(maf_ in mafs_){
    for(hwe_ in hwes_){
      aux = finalPltDf %>% filter(Sample == sample_ , P >= hwe_ , MAF >= maf_)
      saveTabl = aux %>% distinct(SNP)
      print(paste(sample_,maf_,hwe_,nrow(aux),cont))
      write.table(saveTabl[,c('SNP')] , paste0(root,'ListSnpFilters/filter_sample_',sample_,'_maf_',maf_,'_hwe_',hwe_,'.txt'), col.names = F , row.names = F,quote = F)
      cont = cont + 1
    }
  } 
}

##################################################################################################################################
# Relation between volume of snps and cutpoints previous to pruning analysis
##################################################################################################################################

suppressMessages(suppressWarnings(library(dplyr)))
suppressMessages(suppressWarnings(library(ggplot2)))
suppressMessages(suppressWarnings(library(gtable)))

# Defining important plot functions (Manhattan plt)
manhattanPltDf = function(df_,samp_){
#adapted from:https://www.r-graph-gallery.com/101_Manhattan_plot.html
    dfPrep <- df_ %>% 
  # Compute chromosome size
  group_by(CHR) %>% 
  summarise(chr_len=as.numeric(max(BP))) %>% 
  # Calculate cumulative position of each chromosome
  mutate(tot=cumsum(chr_len)-chr_len) %>%
  select(-chr_len) %>%
  # Add this info to the initial dataset
  left_join(df_, ., by=c("CHR"="CHR")) %>%
  # Add a cumulative position of each SNP
  arrange(CHR, BP) %>%
  mutate(BPcum=BP+tot , Samp = samp_)

  axisdf = dfPrep %>% group_by(CHR) %>% summarize(center=( max(BPcum) + min(BPcum) ) / 2 )%>%
  ungroup() %>%
  mutate(Samp = samp_)

  return(list(dfPrep,axisdf))

}

manhattanPlt = function(dfPrep_,axisdf_,cutPoint_,type_){
#adapted from:https://www.r-graph-gallery.com/101_Manhattan_plot.html

  if(type_ == 'hwe'){
    plt0 = ggplot(dfPrep_, aes(x=BPcum, y=-log10(P)))
  } else{
    plt0 = ggplot(dfPrep_, aes(x=BPcum, y=MAF))
  }
    plt = plt0 +
    # Show all points
    geom_point( aes(color=as.factor(CHR)), alpha=0.8, size=1.3) +
    
    # custom X axis:
    scale_x_continuous( label = axisdf_$CHR, breaks= axisdf_$center ) +
    scale_y_continuous(expand = c(0, 0) ) +     # remove space between plot area and x axis

    # Custom the theme:
    theme_bw() +
    theme( 
      legend.position="none",
      panel.border = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank()
    ) +
    geom_hline(yintercept = cutPoint_ , col = 'red') +
    facet_wrap(~Samp , ncol = 1)
    
    return(plt)
}

savePlt = function(df_,sample_,root_,name_){

    dfPlot = df_ %>% filter(Sample == sample_)
    p = manhattanPlt(dfPlot,1e-4)
    ggsave(paste0(root_,name_,".png"), p, bg = "transparent")
    return(p)

}

dfPltManhattanHwe = NULL
dfPltAxisManhattanHwe = NULL
dfPltManhattanMaf = NULL
dfPltAxisManhattanMaf = NULL


names_ = c('Only europeans' , 'Known phenotypes' , 'All genotyped individuals')
filters_ = c('NAfr' , 'Geuvadis' , 'Full')
for(idx_ in 1:3){

    print(paste0('sample:',names_[idx_]))
    auxFiltHwe = finalPltDf %>% filter(Sample == filters_[idx_]) %>% distinct(CHR,SNP,P,Sample,BP)
    auxListHwe = manhattanPltDf(auxFiltHwe,names_[idx_])
    dfPltManhattanHwe = rbind(dfPltManhattanHwe , auxListHwe[[1]])
    dfPltAxisManhattanHwe = rbind(dfPltAxisManhattanHwe , auxListHwe[[2]])
    auxListHwe = NULL
    auxFiltHwe = NULL

}

Sys.time()
plotMHwe = manhattanPlt(dfPltManhattanHwe,dfPltAxisManhattanHwe,4,'hwe')
ggsave(paste0(rootSave,'allFramesHwe2',".png"), plotMHwe, bg = "transparent",width=12, height=6, dpi=300)
Sys.time()

dfTotVol = NULL
cutsHwe = c(.05 , 1e-2 , 1e-3 , 1e-4 , 1e-5 , 1e-6 , 1e-7 , 1e-8 )
cutsMaf = c(.001 , .005 , (1:5)/100)
totSnps = finalPltDf %>% distinct(CHR,SNP) %>% group_by(CHR) %>% summarise(nTot=n()) %>% ungroup()
for(cutHwe_ in cutsHwe){
  for(cutMaf_ in cutsMaf){
    print(paste(cutHwe_,cutMaf_))
    dfCuts = merge(
      finalPltDf %>% filter(P >= cutHwe_ , MAF >= cutMaf_) %>% distinct(Sample,CHR,SNP) %>%  group_by(Sample,CHR) %>% summarise(n=n()) %>% ungroup() %>% mutate(hwe = cutHwe_,maf = cutMaf_)
      ,
      totSnps
    )
    dfTotVol = rbind(dfTotVol,dfCuts)
  }
}


dfBars = rbind(
  dfTotVol %>% select(Sample,CHR,n,hwe,maf)
  ,
  dfTotVol %>% select(Sample,CHR,nTot) %>% rename(n=nTot) %>% mutate(hwe = 0,maf=1)
)

plotVol = dfBars %>% ggplot(aes(x = CHR,y=log10(n) , colour = as.factor(hwe) , linetype = as.factor(maf))) + 
geom_line() +
geom_point() +
facet_wrap(~Sample,ncol = 1) +
theme_bw() +
theme( 
      panel.border = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank()
    ) +
labs(x = 'Chromosome',y= expression(Frequency ~ (log[10]) ) , colour = 'HWE',linetype = 'MAF')

ggsave(paste0(rootSave,'combinedFilters0',".png"), plotVol, bg = "transparent",width=10, height=8, dpi=300)

dfVolSum = dfTotVol %>% group_by(Sample,hwe,maf) %>% summarise(n = sum(n) ) %>% ungroup()
dfVolSum$Tot = sum(totSnps$nTot)
dfVolSum$freqRel = dfVolSum$n/dfVolSum$Tot

plotVolMarg = dfVolSum %>% ggplot(aes(x = -log10(hwe),y=100*freqRel , colour = as.factor(maf) , shape = Sample )) + 
facet_wrap(~Sample, ncol = 1) +
geom_line() +
geom_point(size = 3) +
theme_bw() +
theme( 
      panel.border = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank()
    ) +
labs(x = expression( HWE~ (-log[10]) ),y= 'Relative size of set' , colour = 'MAF')+
scale_y_continuous(breaks = 5*c(0:8) , labels = paste0(5*c(0:8),'%'))
ggsave(paste0(rootSave,'combinedFiltersMarg0',".png"), plotVolMarg, bg = "transparent",width=10, height=8, dpi=300)



dfMaf = NULL
cuts = c(.001 , .005 , (1:5)/100)

for(cut_ in cuts){
  print(cut_)
  dfCuts = merge(
    dfPltManhattanMaf %>% filter(MAF <= cut_) %>% group_by(Sample,CHR) %>% summarise(n=n()) %>% ungroup() %>% mutate(cut = cut_)
    ,
    totSnps
  )
  dfMaf = rbind(dfMaf,dfCuts)
}

dfMaf = dfMaf %>% mutate(freq = n/nTot)

knitr::kable(dfMaf)

plotMafLog = dfMaf %>% ggplot(aes(x = CHR,y=log10(n) , colour = as.factor(cut))) + 
geom_point() +
geom_line() + 
facet_wrap(~Sample,ncol = 1) +
theme_bw() +
theme( 
      panel.border = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank()
    ) +
labs(x = 'Chromosome',y= expression(Frequency ~ (log[10]) ) , colour = 'Cutpoint')

plotMafRelativeFr = dfMaf %>% ggplot(aes(x = CHR,y = freq , colour = as.factor(cut))) + 
geom_point() +
geom_line() + 
facet_wrap(~Sample,ncol = 1) +
theme_bw() +
theme( 
      panel.border = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank()
    ) +
labs(x = 'Chromosome',y= "Relative frequency" , colour = 'Cutpoint')

grobLog = ggplotGrob(plotMafLog)
grobLog = gtable_add_cols(grobLog,unit(0,'mm'))
grobRel = ggplotGrob(plotMafRelativeFr)
grobRel = gtable_add_cols(grobRel,unit(0,'mm'))
bindGrobs = rbind(grobLog,grobRel , size = 'first')


ggsave(paste0(rootSave,'allFramesMafx',".png"), bindGrobs, bg = "transparent",width=10, height=8, dpi=300)

